name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # os: [windows-latest, macOS-latest, ubuntu-latest]
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM
        uses: actions/setup-node@v1
        with:
          node-version: 20
      - name: Increase memory limit
        run: |
          echo "::set-env name=NODE_OPTIONS=--max-old-space-size=4096" >> $GITHUB_ENV
      - name: Build/release Electron app
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install
          npm run build
